eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  config:
    import: optional:config-server:http://localhost:8080/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
          id: car
          uri: http://localhost:8081/
          predicates:
            Path=/api/vehicle/**

spring.cloud.config.enabled: false
